team_names = {
    'arizona':'Arizona Cardinals',
    'atlanta':'Atlanta Falcons',
    'baltimore':'Baltimore Ravens',
    'buffalo':'Buffalo Bills',
    'carolina':'Carolina Panthers',
    'chicago':'Chicago Bears',
    'cincinnati':'Cincinnati Bengals',
    'cleveland':'Cleveland Browns',
    'dallas':'Dallas Cowboys',
    'denver':'Denver Broncos',
    'detroit':'Detroit Lions',
    'green_bay':'Green Bay Packers',
    'houston':'Houston Texans',
    'indianapolis':'Indianapolis Colts',
    'jacksonville':'Jacksonville Jaguars',
    'kansas_city':'Kansas City Chiefs',
    'la_chargers':'Los Angeles Chargers',
    'la_rams':'Los Angeles Rams',
    'las_vegas':'Las Vegas Raiders',
    'miami':'Miami Dolphins',
    'minnesota':'Minnesota Vikings',
    'new_england':'New England Patriots',
    'new_orleans':'New Orleans Saints',
    'ny_giants':'New York Giants',
    'ny_jets':'New York Jets',
    'philadelphia':'Philadelphia Eagles',
    'pittsburgh':'Pittsburgh Steelers',
    'san_francisco':'San Francisco 49ers',
    'seattle':'Seattle Seahawks',
    'tampa_bay':'Tampa Bay Buccaneers',
    'tennessee':'Tennessee Titans',
    'washington':'Washington Commanders'
}