team_names = {
    'arizona': ['Arizona Cardinals', 'Cardinals'],
    'atlanta': ['Atlanta Falcons', 'Falcons'],
    'baltimore': ['Baltimore Ravens', 'Ravens'],
    'buffalo': ['Buffalo Bills', 'Bills'],
    'carolina': ['Carolina Panthers', 'Panthers'],
    'chicago': ['Chicago Bears', 'Bears'],
    'cincinnati': ['Cincinnati Bengals', 'Bengals'],
    'cleveland': ['Cleveland Browns', 'Browns'],
    'dallas': ['Dallas Cowboys', 'Cowboys'],
    'denver': ['Denver Broncos', 'Broncos'],
    'detroit': ['Detroit Lions', 'Lions'],
    'green_bay': ['Green Bay Packers', 'Packers'],
    'houston': ['Houston Texans', 'Texans'],
    'indianapolis': ['Indianapolis Colts', 'Colts'],
    'jacksonville': ['Jacksonville Jaguars', 'Jaguars'],
    'kansas_city': ['Kansas City Chiefs', 'Chiefs'],
    'la_chargers': ['Los Angeles Chargers', 'Chargers'],
    'la_rams': ['Los Angeles Rams', 'Rams'],
    'las_vegas': ['Las Vegas Raiders', 'Raiders'],
    'miami': ['Miami Dolphins', 'Dolphins'],
    'minnesota': ['Minnesota Vikings', 'Vikings'],
    'new_england': ['New England Patriots', 'Patriots'],
    'new_orleans': ['New Orleans Saints', 'Saints'],
    'ny_giants': ['New York Giants', 'Giants'],
    'ny_jets': ['New York Jets', 'Jets'],
    'philadelphia': ['Philadelphia Eagles', 'Eagles'],
    'pittsburgh': ['Pittsburgh Steelers', 'Steelers'],
    'san_francisco': ['San Francisco 49ers', '49ers'],
    'seattle': ['Seattle Seahawks', 'Seahawks'],
    'tampa_bay': ['Tampa Bay Buccaneers', 'Buccaneers'],
    'tennessee': ['Tennessee Titans', 'Titans'],
    'washington': ['Washington Commanders', 'Commanders'],
}
